version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://embeddings100.cloud-stacks.com}
    volumes:
      # Mount for development only - remove for production
      - ./src:/app/src
    restart: unless-stopped

  # Add additional services as needed (e.g., backend API, database)
  # Example:
  # api:
  #   image: your-api-image
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5432/dbname
  #   depends_on:
  #     - db
  #
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=user
  #     - POSTGRES_DB=dbname

# Define volumes if needed
# volumes:
#   postgres_data: